"""
Shared schema for anything the backtest engine consumes.

The single most important rule in this module: **every dataset and every
record knows and declares where it came from.** Nothing downstream
(replay engine, backtest runner, reports) is allowed to treat a dataset
as real unless its `provenance` says so.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from enum import Enum

from core.models.market import PriceBar
from core.models.options import OptionContract


class DataProvenance(str, Enum):
    REAL_ALPACA_HISTORICAL = "REAL_ALPACA_HISTORICAL"
    # Pulled from Alpaca's OptionHistoricalDataClient.get_option_bars() —
    # real market prints, real dates. See scripts/fetch_historical_options.py.

    REAL_USER_SUPPLIED_CSV = "REAL_USER_SUPPLIED_CSV"
    # Loaded from a CSV the operator supplied, in the schema documented in
    # data/market/csv_source.py. Claude cannot verify the CSV's own
    # authenticity — that's on the operator, but it is NOT synthetic.

    SYNTHETIC_OPTIONS_DATA = "SYNTHETIC_OPTIONS_DATA"
    # Generated by data/market/synthetic_source.py using Black-Scholes with
    # documented, disclosed assumptions and a fixed random seed. NEVER to
    # be reported as, compared to, or labeled as real market history.


@dataclass(frozen=True, slots=True)
class HistoricalDay:
    """One trading day's worth of data for one underlying: the underlying's
    own price plus every option contract quote available as of that day."""
    as_of_date: date
    underlying: str
    underlying_close: float
    contracts: tuple[OptionContract, ...]


@dataclass(frozen=True, slots=True)
class HistoricalDataset:
    underlying: str
    provenance: DataProvenance
    days: tuple[HistoricalDay, ...]  # must be sorted ascending by as_of_date
    metadata: dict = field(default_factory=dict)
    # metadata REQUIRED keys by provenance:
    #   REAL_ALPACA_HISTORICAL: {"fetched_at": iso str, "feed": "indicative"|"opra", "date_range": [start, end]}
    #   REAL_USER_SUPPLIED_CSV: {"source_path": str, "date_range": [start, end]}
    #   SYNTHETIC_OPTIONS_DATA: {"pricing_model": "black_scholes_merton", "random_seed": int,
    #                            "underlying_price_source": "real_alpaca"|"synthetic",
    #                            "volatility_assumption": ..., "strike_grid": ...,
    #                            "expiration_grid": ..., "spread_model": ...,
    #                            "transaction_cost_model": ..., "slippage_model": ...}

    @property
    def start_date(self) -> date | None:
        return self.days[0].as_of_date if self.days else None

    @property
    def end_date(self) -> date | None:
        return self.days[-1].as_of_date if self.days else None

    def label(self) -> str:
        """Short string every report/log line should prefix results with."""
        return f"[{self.provenance.value}: {self.underlying} {self.start_date}..{self.end_date}]"

    def as_of_or_earlier(self, cutoff: date) -> "HistoricalDataset":
        """Returns a NEW dataset containing only days at or before cutoff.
        This is the core leakage-prevention primitive — see backtest/replay_engine.py."""
        visible = tuple(d for d in self.days if d.as_of_date <= cutoff)
        return HistoricalDataset(
            underlying=self.underlying, provenance=self.provenance, days=visible, metadata=self.metadata
        )
